Rewrite: use getopts and better error flow.
Added ISO 8601 dates. Requires openssl-3.
New crt2pem script.
Better DER detection.

diff --git a/pki/scripts/certInfo b/pki/scripts/certInfo
--- a/pki/scripts/certInfo
+++ b/pki/scripts/certInfo
@@ -3,18 +3,38 @@
 # (C) Piter.NL
 #
 # Display X590 certificate info
-# Options: -cn ; show Common Name (CN)
+# Options:
+#   -c | --cn      ; Show Common Name (CN)
+#   -s | --subject ; Show Subject
 
+### Arguments/Options
 
-if [ -z "$1" ] ; then
-   echo "usage: <cert>"
-   exit 1
-fi
-
+OPENSSL=openssl-3
 optInfo=1
-if [ "$2" == "-cn" ] ; then
-  optCn=1
-  optInfo=
+optCN=
+optSubject=
+CFILE=
+isKey=
+isPem=
+isDer=
+
+while getopts f-:c-:s-:d-: opt ; do
+   if [ "$opt" = "-" ]; then # --long opt
+       opt="${OPTARG%%=*}"
+   fi
+   case "${opt}" in
+      c | cn) optCn=1;optInfo=;;
+      s | subject) optSubject=1;optInfo=;;
+      d | dates) optDates=1;optInfo=;;
+   esac
+done
+shift $((OPTIND - 1))
+
+CFILE="$1"
+
+if [ -z "$CFILE" ] ; then
+   echo "usage: [-c | --cn | -s | --subject] <cert>"
+   exit 1
 fi
 
 info() {
@@ -23,58 +43,90 @@ info() {
  fi
 }
 
-file="$1"
-
-parseCert() {
- local certInf="$1"
- export SUBJ=$(echo "$certInf" | grep "Subject:" | sed "s/.*Subject:[ ]*\(.*\)/\1/")
- export ISS=$(echo "$certInf" | grep "Issuer:" | sed "s/.*Issuer:[ ]*\(.*\)/\1/")
- export CN=$(echo "$certInf" | grep "Subject:" | grep CN | sed "s/.*CN[ ]*=[ ]*\([^,]*\).*/\1/g")
- export DATE=$(echo "$certInf" | grep "Not Before" | sed -e "s/.*Not.*Before[ ]*: //")
- export EXP=$(echo "$certInf" | grep "Not After" | sed -e "s/.*Not.*After[ ]*: //")
+fatal() {
+  echo "*** Fatal: $*" >&2
+  exit 1
 }
 
-inf=$(openssl x509 -in "$file" -text -noout 2>/dev/null)
-if [ -z "$inf" ] ; then
-   inf=$(openssl x509 -inform der -in "$1" -text -noout 2>/dev/null)
-   stat="$?"
-   if [ "$stat" == "1" ] ; then
-     inf=""
-   fi
-fi
+getInfo() {
+ # Check PEM format:
+ inf=$($OPENSSL x509 -in "$CFILE" -text -noout 2>/dev/null)
+ isPem=$(($? == 0))
+ INFORM=
 
-# check private:
-if [ -z "$inf" ] ; then
-  inf=$(openssl rsa -in "$file" -text 2>/dev/null)
-  isKey=1
-  optInfo=
-fi
+ if [ -z "$inf" ] ; then
+    # Check DER format:
+    inf=$($OPENSSL x509 -inform der -in "$1" -text -noout 2>/dev/null)
+    isDer=$(($? == 0))
+    if [ "$isDer" == "1" ] ; then
+       INFORM="-inform DER"
+    fi
+ fi
 
-if [ -z "$inf" ] ; then
-   echo "*** Not a certificate file: $1"
-   exit 1
-fi
+ # Check private key:
+ if [ -z "$inf" ] ; then
+    inf=$($OPENSSL rsa -in "$CFILE" -text -noout 2>/dev/null)
+    isKey=$(($? == 0))
+ fi
 
-info "=== [x509] ==="
+ if [ -z "$inf" ] ; then
+    fatal "*** Not a certificate file: $1"
+ fi
+
+}
+
+parseCert() {
+ if [ "$isKey" == 1 ] ; then
+    KATTR=$($OPENSSL rsa -noout -modulus $INFORM -in "$CFILE" 2>/dev/null)
+    KEYMOD=$(echo "$KATTR" | grep Modulus | sed "s/.*Modulus=[ ]*\(.*\)/\1/")
+    return;
+ fi
+
+ CATTR=$($OPENSSL x509 -noout -subject -issuer -dates -dateopt iso_8601 -serial -modulus $INFORM -in "$CFILE" 2>/dev/null)
+ if [ "$?" != "0" ] ; then
+    fatal "File not found or is not a certificate: $CFILE"
+ fi
+ SUBJ=$(echo "$CATTR" | grep subject= | sed "s/.*subject=[ ]*\(.*\)/\1/")
+ ISS=$(echo "$CATTR" | grep issuer= | sed "s/.*issuer=[ ]*\(.*\)/\1/")
+ CN=$(echo "$CATTR" | grep subject= | sed "s/.*CN[ ]*=[ ]*\([^,]*\).*/\1/g")
+ DATE=$(echo "$CATTR" | grep notBefore | sed "s/.*notBefore=[ ]*\(.*\)/\1/")
+ EXP=$(echo "$CATTR" | grep notAfter | sed "s/.*notAfter=[ ]*\(.*\)/\1/")
+ SERIAL=$(echo "$CATTR" | grep serial | sed "s/.*serial=[ ]*\(.*\)/\1/")
+ CERTMOD=$(echo "$CATTR" | grep Modulus | sed "s/.*Modulus=[ ]*\(.*\)/\1/")
+}
+
+getInfo "$CFILE"
+
+info " [x509] "
 info "$inf"
 
 parseCert "$inf"
 
-if [ -n "$optInfo" ] ; then
-  info  "=== [summary] ==="
-  info " - SUBJECT : \"$SUBJ\""
-  info " - ISSUER  : \"$ISS\""
-  info " - CN      : \"$CN\""
-  info " - ISSUED  : \"$DATE\""
-  info " - EXPIRE  : \"$EXP\""
+if [ "$isKey" == 1 ] ; then
+   info " [summary] "
+   info " - <private key>"
+   info " - KEY MOD : $KEYMOD"
+else
+   info " [summary] "
+   info " - SUBJECT  : $SUBJ"
+   info " - ISSUER   : $ISS"
+   info " - SERIAL   : $SERIAL"
+   info " - CN       : $CN"
+   info " - ISSUED   : $DATE"
+   info " - EXPIRE   : $EXP"
+   info " - CERT MOD : $CERTMOD"
+   info " [flags] "
+   info " - isPem    : $isPem"
+   info " - isDer    : $isDer"
+   info " - isKey    : $isKey"
 fi
 
-if [ -n "$optCn" ] ; then
-  if [ -n "$isKey" ] ; then
-    echo "<private key>"
-  else
-     echo "${CN}"
-  fi
+if [ -n "$isKey" ] ; then
+   echo "<private key>"
+else
+   [ -n "$optCn" ] && echo "CN:${CN}"
+   [ -n "$optSubject" ] && echo "subject:${SUBJ}"
+   [ -n "$optDates" ] && echo "notBefore:${DATE}" && echo "notAfter:${EXP}"
 fi
 
-#end
+# end
diff --git a/pki/scripts/p12Add b/pki/scripts/p12Add
--- a/pki/scripts/p12Add
+++ b/pki/scripts/p12Add
@@ -4,25 +4,37 @@
 #
 # Add certs to new or existing p12.
 
-# Arguments:
+### Arguments:
 
 P12="$1"
 shift
-PASS="$1"
-shift
+if [ "$1" == "-p" ] ; then
+  shift
+  PASS="$1"
+  PASSOPT="-passin pass:$PASS"
+  PASSOUT="-passout pass:$PASS"
+  shift
+fi
+
 CERTS="$@"
 
 if [ -z "$CERTS" ] ; then
-    echo "usage: <p12> <password> <cert> [ <certs...> ]; <cert> or <certs> can be list of file or wildcard: cert/*.pem"
+    echo "usage: <p12> [-p <password>] <cert> [ <certs...> ]; <cert> or <certs> can be list of files or wildcard: cert/*.pem"
     exit 1
 fi
 
-### derived
+### Derived
+
 CERTDIR="certs"
 P12NEW=$(echo "$P12" | sed "s/\.p12/-new.p12/")
 PASSFILE=$(echo "$P12" | sed "s/\.p12/-password.txt/")
 
-# switch
+fatal() {
+  echo "*** Fatal: $*" >&2
+  exit 1
+}
+
+### switch
 
 if [ -f ${P12} ]  ; then
    echo "Use existing certstore [yY/nN]: $P12"
@@ -43,16 +55,15 @@ echo " - pass       :'${PASS}'"
 echo " - CERT       :'${CERTS}'"
 echo " - CERTDIR    :'${CERTDIR}'"
 
-
 mkdir -pv "${CERTDIR}"
 
 if [ -f "$P12" ] ; then
-  p12Extract "$P12" "$PASS"
+  p12Extract "$P12" "$PASS" || fatal "Failed to extract key/truststore:$P12"
 else
   echo " - Skipping extracting: no existing: $P12"
 fi
 
-# Add new certs:
+### Add new certs:
 
 certFiles=`ls $CERTS`
 for f in $certFiles ; do
@@ -71,9 +82,10 @@ if [ "$ans" != "y" ] && [ "$ans" != "Y" ] ; then
 	exit 1
 fi
 
-openssl pkcs12 -export -nokeys -in "${CERTDIR}/allcerts.pemz" -out "$P12NEW" -password "pass:$PASS"
+openssl pkcs12 -export -nokeys -in "${CERTDIR}/allcerts.pemz" $PASSOUT -out "$P12NEW" || fatal "Failed to create new keystore:$P12NEW"
 echo "$PASS" > $PASSFILE
 
 echo " - Created: $P12NEW"
 echo " - Created: $PASSFILE"
 
+# end
diff --git a/pki/scripts/p12Extract b/pki/scripts/p12Extract
--- a/pki/scripts/p12Extract
+++ b/pki/scripts/p12Extract
@@ -3,42 +3,51 @@
 # (C) Piter.NL
 #
 # Extract certs in p12 store to 'certs/' directory
-# usage: [ <p12file> <paswd> ] | [ -pems certificates.pems ]
+# Usage: <p12file> [ <passwd> ] | -p|--pems certificates.pem[s]
 #
 
-# Arguments:
+### Arguments/Options
 
 FILE=
 PWD=
 USEPEMS=
 PEMS=
-CSPLIT=$(which gcsplit >/dev/null && echo gcsplit || echo csplit)
+CSPLIT=$(which gcsplit 1>/dev/null 2>&1 && echo gcsplit || echo csplit)
 
-if [ "$1" == "-pems" ] ; then
-  FILE=
-  PWD=
-  PEMS="$2"
-  USEPEMS=1
-  if [ -z "$PEMS" ] ; then
-    echo "usage: -pems <pemsFile>"
-  exit 1
-  fi
-else
-  USEPEMS=
-  PEMS=
+while getopts f:p-: opt ; do
+   if [ "$opt" = "-" ]; then # --long opt
+       opt="${OPTARG%%=*}"
+       arg="${OPTARG#"$OPT"}" # argument
+   fi
+   case "${opt}" in
+      p | pems) FILE=;PWD=;PEMS=$arg;USEPEMS=1;;
+   esac
+done
+shift $((OPTIND - 1))
+
+if [ "$USEPEMS" != "1" ] ; then
   FILE="$1"
   PWD="$2"
-  if [ -z "$PWD" ] ; then
-     echo "usage: <p12> <password>"
+  if [ -n "$PWD" ] ; then
+     PASSOPT="-passin pass:$PWD"
+  fi
+  if [ -z "$FILE" ] ; then
+     echo "usage: <p12> [ <password> ] | -p | --pems <pemfile>"
      exit 1
   fi
 fi
 
-# Parameters:
+### Parameters:
+
 OUT=certs
 P12OUT="${OUT}/pk12certs.pems"
 KEYOUT="${OUT}/private-key.pem"
 CERT_PREFIX=cert_
+
+fatal() {
+  echo "*** Fatal: $*" >&2
+  exit 1
+}
 
 # Init
 mkdir -vp "$OUT"
@@ -47,14 +56,13 @@ mkdir -vp "$OUT"
 if [ -z "$USEPEMS" ] ; then
   echo " - certfile : $FILE"
   echo " - outdir   : $OUT"
-  openssl pkcs12 -nokeys -in "$FILE" -info -passin "pass:$PWD" |\
-  sed -n "/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/{p;}" > "$P12OUT"
+  pems=$(openssl pkcs12 -nokeys -in "$FILE" -info $PASSOPT) || fatal "Invalid password or not a key/truststore: $FILE"
+  echo "$pems" | sed -n "/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/{p;}" > "$P12OUT"
 
   # privates:
-  openssl pkcs12 -in "$FILE" -out "${KEYOUT}" -nodes -nocerts -passin "pass:$PWD"
-
+  openssl pkcs12 -in "$FILE" -out "${KEYOUT}" -nodes -nocerts $PASSOPT
 else
-  cp -vf $PEMS $P12OUT
+   cp -vf $PEMS $P12OUT
 fi
 
 # csplit: Note: first cert_00 file contains empty space:
@@ -65,10 +73,11 @@ rm -vf ${OUT}/${CERT_PREFIX}00.pem
 # certInfo:
 echo " - certs: "$(ls $OUT/*.pem)
 
-for f in $(cd "$OUT"; ls *.pem) ; do
-    BASE=$(echo $f | sed "s/.pem//")
+for CFILE in $(cd "$OUT"; ls *.pem) ; do
+    BASE=$(echo $CFILE | sed "s/.pem//")
     OUTFILE="${OUT}/${BASE}.txt"
-    echo " - $OUTFILE : $(certInfo "$OUT/$f" -cn)"
-    certInfo "$OUT/$f" > "$OUTFILE"
+    echo " - $OUT/$CFILE : '$(certInfo --cn "$OUT/$CFILE")'"
+    certInfo "$OUT/$CFILE" > "$OUTFILE"
 done
 
+# end
